version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - post-rpc-{{ checksum "package.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: post-rpc-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - post-rpc-{{ checksum "package.json" }}
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Run Test
          command: npm run test

workflows:
  version: 2
  post_rpc:
    jobs:
      - build
      - test:
          requires:
            - build
